### ISSUE TITLE
CA1813: Microsoft.Performance : Seal 'TimestampAttribute', if possible.

### ISSUE THREAD

**Issue by buddde** [SimonCropp/Timestamp#11]
Hello,

when I use your nuget package and build my project with code analysis on, I get the following warning:

**MSBUILD : warning CA1813: Microsoft.Performance : Seal 'TimestampAttribute', if possible.**

Could you please seal your attribute, as microsoft suggests here:
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1813-avoid-unsealed-attributes

Thank you.

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.

**Comment by buddde** [comment]
Works like a charm.

Thank you for your quick response.

**Comment by SimonCropp** [comment]
No worries. Btw r u using git for source control?

**Comment by buddde** [comment]
No, I'm using "TFS on premises".

Btw, I'm having problems with your package in a .NET Core 2.2. project. Should it work?

**Comment by SimonCropp** [comment]
Dont know about netcore 2.2. Not tried it there
